// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW8d-y3_-SvRn223P-kqTUsCkRN5kKn7U',
    appId: '1:167315489149:web:a24d3f724aba215b594c14',
    messagingSenderId: '167315489149',
    projectId: 'dropdost11',
    authDomain: 'dropdost11.firebaseapp.com',
    storageBucket: 'dropdost11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZwsBp_E2Hb8CWXAUwVWMYm2F0VfxOn7Q',
    appId: '1:167315489149:android:5cec7b42eae5afca594c14',
    messagingSenderId: '167315489149',
    projectId: 'dropdost11',
    storageBucket: 'dropdost11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0izMiNoBUg6QrxOLLQB8A0YN8g_ZpIRE',
    appId: '1:167315489149:ios:8fa96acb398874ed594c14',
    messagingSenderId: '167315489149',
    projectId: 'dropdost11',
    storageBucket: 'dropdost11.firebasestorage.app',
    iosBundleId: 'com.example.dropdost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0izMiNoBUg6QrxOLLQB8A0YN8g_ZpIRE',
    appId: '1:167315489149:ios:8fa96acb398874ed594c14',
    messagingSenderId: '167315489149',
    projectId: 'dropdost11',
    storageBucket: 'dropdost11.firebasestorage.app',
    iosBundleId: 'com.example.dropdost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW8d-y3_-SvRn223P-kqTUsCkRN5kKn7U',
    appId: '1:167315489149:web:cfe02294a2dda0c2594c14',
    messagingSenderId: '167315489149',
    projectId: 'dropdost11',
    authDomain: 'dropdost11.firebaseapp.com',
    storageBucket: 'dropdost11.firebasestorage.app',
  );

}